apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-creds
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: {{ template "pgbouncer.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  postgresql-password: {{ default "" .Values.password | b64enc | quote }}
