apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-probes-settings
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: {{ template "pgbouncer.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  probes_query: {{ .Values.probes.query | b64enc | quote }}
  probes_username: {{ default .Values.username .Values.probes.username | b64enc | quote }}
  probes_password: {{ default .Values.password .Values.probes.password| b64enc | quote }}
  probes_database: {{ .Values.probes.database | b64enc | quote }}
