apiVersion: v1
kind: Service
metadata:
  name: {{ template "pgbouncer.fullname" . }}
  labels:
    app: {{ template "pgbouncer.name" . }}
    chart: {{ template "pgbouncer.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: pgbouncer
    port: 5432
    targetPort: pgbouncer
  selector:
    app: {{ template "pgbouncer.name" . }}
